### ISSUE TITLE
New Collaborators

### ISSUE THREAD

**Issue by kevinskyba** [kevinskyba/kickbase-api-doc#4]
@simonsagstetter @casudo are now collaborators in this project. Feel free to update the documentations for others and add yourself to the readme.

**Comment by simonsagstetter** [comment]
@kevinskyba thanks for the invitation. 

@casudo and I are going to update the documentation to v4. I'll suggest by starting to create new branches:

1. Copy the current master to a new "v1" branch and mark it as stale
2. Create a new branch "v4" and set it to the master branch or even set v4 to the main branch
3. Update v4 with newest postman collection, swagger collection and swaggerui html file for the github page
4. Update Readme 
5. Roadmap: Complete the request bodies, response body descriptions 

WDYT? If you like the idea I'll start creating the new branches later that evening.

**Comment by casudo** [comment]
Alternatively create a release "as is" and name it v1. After that, we could update it to v4 via PR. The main branch would then automatically be the v4 branch.

With every update in the endpoints we simply can create a new release.

**Comment by simonsagstetter** [comment]
I personally like the idea of versioning with different branches when there is no real benefit of a creating a release because of the type of project this repo is.

But in this case I guess no one will ever need the legacy endpoints again because they have been removed. So lets go with the release.

**Comment by casudo** [comment]
I've created the release for the legacy endpoints. 👍🏽
