### ISSUE TITLE
Kickbase-Api: Spieler der aktuellen Saison 

### ISSUE THREAD

**Issue by AlexKipke** [kevinskyba/kickbase-api-doc#5]
Hallo,

zurzeit baue ich ein Hilfstool für Kickbase und wollte fragen, ob es über die aktuelle v4 API eine Möglichkeit gibt, sich alle Spieler dieser Saison anzeigen zu lassen. Ich habe mir alle Endpunkte angeschaut, aber nichts Direktes gefunden, da man anscheinend immer die playerID als Parameter benötigt.

Eine Idee, die ich mir vorstellen könnte, wäre, den folgenden Endpunkt zu nutzen: 

https://api.kickbase.com/v4/leagues/{{leagueId}}/players/{{playerId}}/performance

indem man eine Schleife laufen lässt und die playerID schrittweise erhöht. So könnte man alle Spieler erfassen, die Einträge zur Saison 24/25 haben.

Dabei sehe ich allerdings folgende Probleme:

- Die API könnte meine IP blockieren, weil zu viele Anfragen gesendet werden.
- Wie weit sollte man bei der playerID zählen?

Vielleicht hat jemand eine effizientere Methode, die ich übersehen habe.

**Comment by simonsagstetter** [comment]
Hi @AlexKipke,

ich knüpfe da mal an das bereits gute beispiel von @casudo mit einem javascript snippet an, wie ich es machen würde.
Du kannst auch verschiedene Endpoints kombinieren, um an das Ziel zu kommen. 

1. Tabelle und Team Ids abrufen
`https://api.kickbase.com/v4/competitions/:competitionId/table`
```
const {it: tableArray} = await fetch("https://api.kickbase.com/v4/competitions/1/table")
const teamIds = tableArray.map(team=>team.tid)
```

2. Alle Spieler der Teams abrufen
`https://api.kickbase.com/v4/competitions/:competitionId/teams/:teamId/teamprofile`

```
const promises = teamIds.map(async(id)=>{
 const {it: teamPlayers} = await fetch(`https://api.kickbase.com/v4/competitions/1/teams/${id}/teamprofile`)
 return teamPlayers;
})

const results = await Promise.all(promises);
const allPlayers = results.flat(); // Das sind alle Spieler der Saison

```

Wenn du etwas Abstand zwischen den Abfragen lässt, sollte das kein Problem sein. Wahrscheinlich wird der Großteil der Anfragen auf Kickbase in der App gecached, weswegen übermäßige Abfragen natürlich auffällig sein können. Ich würde dir empfehlen, dir zum Testen die API Responses abzuspeichern und dir eine Mock Response zu bauen. 

Viel Erfolg!

**Comment by AlexKipke** [comment]
@simonsagstetter @casudo 

Perfekt, danke euch für die schnelle Hilfe !

**Comment by AlexKipke** [comment]
Hallo @casudo ,

mir ist bei der Nutzung des Endpunktes
`https://api.kickbase.com/v4/competitions/1/teams/<team_id>/teamprofile`

ein Fehler aufgefallen.

Man bekommt dort in `"it"` alle spieler aufgelistet.

Anschließend kann man dann für jeden Spieler sehen, ob dieser gerade im Besitzt eines Managers ist oder nicht. Das sieht man anhand der `"onm"` property.

Nun zum eigentlichen Fehler:

Es gibt Spieler, bei welchen die `"onm"` property nicht angegeben ist, die aber in der Kickbase app definitiv einen Besitzer haben

Das konnte ich stichprobenartig bei mehreren Spielern feststellen. Kannst du mal bei dir schauen, ob du den Fehler nachvollziehen kannst ?

**Comment by casudo** [comment]
Hi Alex, ich bin jetzt ebenfalls stichprobenartig mehrere Teams durchgegangen und musste feststellen, dass ich bei keinem einzigen Tea/Spieler den "onm" Parameter auffinden konnte.

**Comment by AlexKipke** [comment]
Ich habe den falschen Endpunkt rein kopiert.
Bei dem genannten gibt es den  "onm" Parameter nicht

Ich meinte diesen hier 

`https://api.kickbase.com/v4/leagues/:leagueId/teams/:teamId/teamprofile/`

habe es auch im Kommentar angepasst

**Comment by simonsagstetter** [comment]
Hi Alex,

ich kann definitiv bestätigen das die `onm` object property innerhalb des`it` arrays nur dann definiert ist, wenn der Spieler im Kader eine Manager der Liga ist. Ist sie nicht definiert, dann ist der Spieler im Besitz von Kickbase und wird früher oder später auf den aktiven Transfermarkt rotiert.

Das lässt sich andersrum über den endpoint `/v4/competitions/:competitionId/players/:playerId` bestätigen.

Ich konnte aber leider noch nicht reproduzieren, dass die `onm` property undefiniert ist, der Spieler aber im Kader eines Managers ist. Hast du das beides per API Aufruf überprüft oder hast du es in der Kickbase App nachgeprüft? Kann gerne sein dass manche Ergebnisse in der App gecached sind. Das wäre meine einzige Idee für diese Anomalie... :(

Vielleicht kannst du einen Response Body mit den zugehörigen Abfragen in den Issue posten?

**Comment by AlexKipke** [comment]
Hier ist der API Aufruf mit dem Beispiel Waldemar Anton vom BVB. Hier müsste die onm property definiert sein.
![image](https://github.com/user-attachments/assets/1953acc4-daa5-4c1b-acb8-a7c51803809b)

Ist definitiv im Besitz eines Managers, wie man am Manager Profilbild sieht.
![image](https://github.com/user-attachments/assets/4d1eda2c-3e85-44d7-a596-2d232931b064)

Dieses Verhalten ist mir noch bei zwei weiteren Spieler aufgefallen. Diese Spieler sind auch sind auch schon seid mehreren Monaten im Besitzt, sodass ich Caching evtl ausschließen. Ich kann es mir nicht erklären.

**Comment by simonsagstetter** [comment]
Kann es sein dass du bei `https://api.kickbase.com/v4/leagues/:leagueId/teams/:teamId/teamprofile/` das Team Profil innerhalb einer anderen Liga abrufst? Ein Tippfehler in der `:leagueId`?

Denn `/v4/competitions/:competitionId/players/:playerId` erhälst du die Informationen, wer den Spieler besitzt, jewels für jede Liga, in der du spielst. Das kannst du auch in der App sehen in Competitions>Tabelle>Dortmund>Anton und dann nach unten scrollen.

**Comment by simonsagstetter** [comment]
@AlexKipke ist der issue noch aktuell? Würde den sonst abschließen...

**Comment by AlexKipke** [comment]
Hallo, 

@simonsagstetter leider ist der Issue immer noch Aktuell. Also ich habe mich definitiv nicht bei der LeagueID vertippt.
.

**Comment by simonsagstetter** [comment]
> Hallo,
> 
> [@simonsagstetter](https://github.com/simonsagstetter) leider ist der Issue immer noch Aktuell. Also ich habe mich definitiv nicht bei der LeagueID vertippt. .

Hi Alex, ich kann den Fehler leider nach wie vor nicht repoduzieren. Wäre es möglich, dass uns das code snippet teilst, bei dem der Issue auftritt? Ansonsten kann ich dir nur schwer helfen...

**Comment by AlexKipke** [comment]
@simonsagstetter bei mir tritt der Fehler im Postman auf. 
Es geht immer noch um diesen GET request:
`https://api.kickbase.com/v4/leagues/:leagueId/teams/:teamId/teamprofile/`

Hier wird mir für Olise kein Besitzer angezeigt, obwohl dieser Definitiv in einem Team ist.

![Image](https://github.com/user-attachments/assets/f241421f-835c-4b72-94b6-281bd9ff1d14)


Das fällt mir noch bei einigen wenigen Spielern auf.

**Comment by simonsagstetter** [comment]
> [@simonsagstetter](https://github.com/simonsagstetter) bei mir tritt der Fehler im Postman auf. Es geht immer noch um diesen GET request: `https://api.kickbase.com/v4/leagues/:leagueId/teams/:teamId/teamprofile/`
> 
> Hier wird mir für Olise kein Besitzer angezeigt, obwohl dieser Definitiv in einem Team ist.
> 
> ![Image](https://github.com/user-attachments/assets/f241421f-835c-4b72-94b6-281bd9ff1d14)
> 
> Das fällt mir noch bei einigen wenigen Spielern auf.

Hi Alex,

ich habe das in meiner Kickbase App und mit den API Reponses nochmal nachgeprüft und bei mir ist die eigenschaft "onm" immer definiert, wenn ich oder ein anderer Manager den Spieler besitzt. Ich kann die von dir beschriebene Anomalie leider nicht reproduzieren.

Es ist schon ein komischer Bug, weil wenn es ein Caching Fehler ist, dann müsste ja entweder die "onm" eigenschaft vorhanden sein oder der Spieler hat keinen Besitzer, der alte Besitzer oder irgendeine anderer Manager wird noch angezeigt.

Ich möchte mich da nicht zu weit aus dem Fenster lehnen, kann aber sagen, dass Kickbase in den ersten Jahren sehr chaotisch war mit deren API. Ich könnte mir vorstellen, dass sie intern nur noch den Competitions Endpoint mit der "onm" eigenschaft verwenden oder es mittlerweile einen neuen gibt. Vielleicht ist die "onm" eigenschaft intern als veraltet makiert im league endpoint und wird nicht mehr geupdated. 

Ich kann dir da auch leider nicht mehr weiterhelfen. Bis es dafür irgendeinen Aufschluss gibt, musst du wohl den Workaround über den Competition Endpoint nehmen. Sorry! :)
